[platformio]
;default_envs = m5core2
;default_envs = m5core2-SD
;default_envs = m5core2-sdu
default_envs = m5core2-sdu-SD
; default_envs = m5coreS3
; default_envs = m5coreS3-SD


[env]
platform = espressif32
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
build_type = release

monitor_filters =
	esp32_exception_decoder
    time
;   log2file

build_flags=
    -D RELEASE
    -DCORE_DEBUG_LEVEL=2 ;0:None, 1:Error, 2:Warn, 3:Info, 4:Debug, 5:Verbose
    ; -Wno-deprecated-declarations 
    ; -Wno-cpp
    ;-Wcpp
    
lib_deps =
    m5stack/M5Unified
    WebServer
    https://github.com/d-a-v/ESPWebDAV
	tobozo/M5Stack-SD-Updater


[sd-updater]
build_flags=
    -DENABLE_SD_UPDATER

[sd-select]
build_flags=
    -DENABLE_SD_SELECT


;---- Core2 v1.0/v1.1/AWS ----
[env:m5core2]
board = m5stack-core2
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.filesystem = spiffs
build_flags =
    -DBOARD_HAS_PSRAM


[env:m5core2-SD]
extends = env:m5core2
build_flags = ${env:m5core2.build_flags} ${sd-select.build_flags}


;-- Core2 v1.0/AWS -- excluding v1.1
[env:m5core2-sdu]
extends = env:m5core2, sd-updater
board_build.partitions = default_16MB.csv
build_flags = ${env:m5core2.build_flags} ${sd-updater.build_flags}


[env:m5core2-sdu-SD]
extends = env:m5core2, sd-updater
board_build.partitions = default_16MB.csv
build_flags = ${env:m5core2.build_flags} ${sd-updater.build_flags} ${sd-select.build_flags}


;---  CoreS3/SE ----
[env:m5coreS3]
board = m5stack-cores3
board_build.arduino.memory_type = qio_qspi
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.filesystem = spiffs
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1


[env:m5coreS3-SD]
extends = env:m5coreS3
build_flags = ${env:m5core3.build_flags} ${sd-select.build_flags}

