
[platformio]
;default_envs = m5core2
default_envs = m5core2-sdu-SPIFFS
; default_envs = m5coreS3


[env]
platform = espressif32
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
build_type = release

monitor_filters =
	esp32_exception_decoder
    time
;   log2file

build_flags=
    ; -D RELEASE
    -DCORE_DEBUG_LEVEL=0 ;0:None, 1:Error, 2:Warn, 3:Info, 4:Debug, 5:Verbose
    -Wno-deprecated-declarations
    -Wcpp
    ; -Wno-cpp

lib_deps =
    m5stack/M5Unified
    WebServer
    https://github.com/d-a-v/ESPWebDAV


[sd-updater]
build_flags=
    -DENABLE_SD_UPDATER
lib_deps = 
	tobozo/M5Stack-SD-Updater

[sd-select]
build_flags=
    -DENABLE_SD_SELECT

[env:m5core2]
;-- Core2 v1.0/v1.1/AWS --
board = m5stack-core2
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.filesystem = spiffs
build_flags =
    -DBOARD_HAS_PSRAM

[env:m5core2-sdu-SPIFFS]
;-- Core2 v1.0/AWS -- excluding v1.1
extends = env:m5core2, sd-updater
board_build.partitions = default_16MB.csv
build_flags = ${env:m5core2.build_flags} ${sd-updater.build_flags}
lib_deps = ${env:m5core2.lib_deps} ${sd-updater.lib_deps}

[env:m5core2-sdu-SD]
;-- Core2 v1.0/AWS -- excluding v1.1
extends = env:m5core2, sd-updater
board_build.partitions = default_16MB.csv
build_flags = ${env:m5core2.build_flags} ${sd-updater.build_flags} ${sd-select.build_flags}
lib_deps = ${env:m5core2.lib_deps} ${sd-updater.lib_deps}


[env:m5coreS3-SPIFFS]
;-- CoreS3/SE --
board = m5stack-cores3
board_build.arduino.memory_type = qio_qspi
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.filesystem = spiffs
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

[env:m5coreS3-SD]
;-- CoreS3/SE --
board = m5stack-cores3
board_build.arduino.memory_type = qio_qspi
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.filesystem = spiffs
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DENABLE_SD_SELECT


